Public Class WriteNewCompatValues
    Public Shared Sub WriteNewCompatValuesToCompat()
        Form1.ComboBoxAPBCompatSection.SelectedItem = Form1.ComboBoxAPBCompatSection.SelectedItem.ToString
        DeclareCompatVarialbes.DeclareCompatVariablesAgain()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "StaticDecals", Form1.CheckBoxStaticDecals.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DynamicDecals", Form1.CheckBoxDynamicDecals.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "LevelParticles", Form1.CheckBoxLevelParticles.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DynamicLights", Form1.CheckBoxDynamicLights.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DynamicShadows", Form1.CheckBoxDynamicShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "BlobShadows", Form1.CheckBoxBlobShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "LightEnvironmentShadows", Form1.CheckBoxLightEnvironmentShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "EnvironmentShadows", Form1.CheckBoxEnvironmentShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "CompositeDynamicLights", Form1.CheckBoxCompositeDynamicLights.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DirectionalLightmaps", Form1.CheckBoxDirectionalLightmaps.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MotionBlur", Form1.CheckBoxMotionBlur.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DepthOfField", Form1.CheckBoxDepthOfField.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "AmbientOcclusion", Form1.CheckBoxAmbientOcclusion.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "Bloom", Form1.CheckBoxBloom.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "QualityBloom", Form1.CheckBoxQualityBloom.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "Distortion", Form1.CheckBoxDistortion.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DropParticleDistortion", Form1.CheckBoxDropParticleDistortion.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SpeedTreeLeaves", Form1.CheckBoxSpeedTreeLeaves.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SpeedTreeFronds", Form1.CheckBoxSpeedTreeFronds.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "OnlyStreamInTextures", Form1.CheckBoxOnlyStreamInTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "LensFlares", Form1.CheckBoxLensFlares.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "FogVolumes", Form1.CheckBoxFogVolumes.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "FloatingPointRenderTargets", Form1.CheckBoxFloatingPointRenderTargets.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "Trilinear", Form1.CheckBoxTrilinear.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "OneFrameThreadLag", Form1.CheckBoxOneFrameThreadLag.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "UseVsync", Form1.CheckBoxUseVsync.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "UpscaleScreenPercentage", Form1.CheckBoxUpscaleScreenPercentage.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "Fullscreen", Form1.CheckBoxFullscreen.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "AllowD3D10", Form1.CheckBoxAllowD3D10.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "EnableHighPolyChars", Form1.CheckBoxEnableHighPolyChars.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SkeletalMeshLODBias", Form1.TextBoxSkeletalMeshLODBias.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ParticleLODBias", Form1.TextBoxParticleLODBias.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "DetailMode", Form1.TextBoxDetailMode.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFilterQualityBias", Form1.TextBoxShadowFilterQualityBias.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxAnisotropy", Form1.TextBoxMaxAnisotropy.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "AnisotropyAmount", Form1.TextBoxAnisotropyAmount.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMultisamples", Form1.TextBoxMaxMultisamples.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MSAA_Amount", Form1.TextBoxMSAA_Amount.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MinShadowResolution", Form1.TextBoxMinShadowResolution.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxShadowResolution", Form1.TextBoxMaxShadowResolution.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFadeResolution", Form1.TextBoxShadowFadeResolution.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFadeExponent", Form1.TextBoxShadowFadeExponent.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFadeStartDistance", Form1.TextBoxShadowFadeStartDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFadeEndDistance", Form1.TextBoxShadowFadeEndDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxDynamicShadows", Form1.TextBoxMaxDynamicShadows.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SunRenderQuality", Form1.TextBoxSunRenderQuality.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TrueSunMinScreenSize", Form1.TextBoxTrueSunMinScreenSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ParticleMaxWorldSpaceArea", Form1.TextBoxParticleMaxWorldSpaceArea.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ScreenPercentage", Form1.TextBoxScreenPercentage.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SceneCaptureStreamingMultiplier", Form1.TextBoxSceneCaptureStreamingMultiplier.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "FoliageDrawRadiusMultiplier", Form1.TextBoxFoliageDrawRadiusMultiplier.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowTexelsPerPixel", Form1.TextBoxShadowTexelsPerPixel.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bEnableVSMShadows", Form1.CheckBoxbEnableVSMShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bEnableBranchingPCFShadows", Form1.CheckBoxbEnableBranchingPCFShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bAllowBetterModulatedShadows", Form1.CheckBoxbAllowBetterModulatedShadows.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bEnableForegroundShadowsOnWorld", Form1.CheckBoxbEnableForegroundShadowsOnWorld.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowFilterRadius", Form1.TextBoxShadowFilterRadius.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowDepthBias", Form1.TextBoxShadowDepthBias.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowVolumeLightRadiusThreshold", Form1.TextBoxShadowVolumeLightRadiusThreshold.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "ShadowVolumePrimitiveScreenSpacePercentageThreshold", Form1.TextBoxShadowVolumePrimitiveScreenSpacePercentageThreshold.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nNumCharacterLOD", Form1.TextBoxnNumCharacterLOD.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterDiffuseWidth", Form1.TextBoxnCharacterDiffuseWidth.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterDiffuseHeight", Form1.TextBoxnCharacterDiffuseHeight.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterNormalMapWidth", Form1.TextBoxnCharacterNormalMapWidth.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterNormalMapHeight", Form1.TextBoxnCharacterNormalMapHeight.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCharacterGenerateUVBleedMesh", Form1.CheckBoxbCharacterGenerateUVBleedMesh.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "m_bGameRenderEyelashes", Form1.CheckBoxm_bGameRenderEyelashes.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCharacterLODDistance1", Form1.TextBoxfCharacterLODDistance1.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCharacterLODDistance2", Form1.TextBoxfCharacterLODDistance2.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCharacterCullDistance", Form1.TextBoxfCharacterCullDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCharacterForceGCAfterBuild", Form1.CheckBoxbCharacterForceGCAfterBuild.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nNumVehicleLOD", Form1.TextBoxnNumVehicleLOD.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorTextureSize", Form1.TextBoxnVehicleExteriorTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorNormalTextureSize", Form1.TextBoxnVehicleExteriorNormalTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorEmissiveTextureSize", Form1.TextBoxnVehicleExteriorEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleInteriorTextureSize", Form1.TextBoxnVehicleInteriorTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleInteriorEmissiveTextureSize", Form1.TextBoxnVehicleInteriorEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleWheelTextureSize", Form1.TextBoxnVehicleWheelTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleWheelEmissiveTextureSize", Form1.TextBoxnVehicleWheelEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleGlassTextureSize", Form1.TextBoxnVehicleGlassTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bVehicleGenerateUVBleedMesh", Form1.CheckBoxbVehicleGenerateUVBleedMesh.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bVehicleForceGCAfterBuild", Form1.CheckBoxbVehicleForceGCAfterBuild.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fVehicleLODDistance", Form1.TextBoxfVehicleLODDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fVehicleCullDistance", Form1.TextBoxfVehicleCullDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nGraffitiTextureWidth", Form1.TextBoxnGraffitiTextureWidth.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nGraffitiTextureHeight", Form1.TextBoxnGraffitiTextureHeight.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCAM_MemoryThresholdNormal", Form1.TextBoxfCAM_MemoryThresholdNormal.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCAM_MemoryThresholdCritical", Form1.TextBoxfCAM_MemoryThresholdCritical.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fCAM_MemoryBackToNormalHysteresis", Form1.TextBoxfCAM_MemoryBackToNormalHysteresis.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCPedestrianLODDistance", Form1.TextBoxfLCPedestrianLODDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCPedestrianCullDistance", Form1.TextBoxfLCPedestrianCullDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCDriverLODDistance", Form1.TextBoxfLCDriverLODDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCDriverCullDistance", Form1.TextBoxfLCDriverCullDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCVehicleLODDistance", Form1.TextBoxfLCVehicleLODDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fLCVehicleCullDistance", Form1.TextBoxfLCVehicleCullDistance.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nMaxMemoryCacheEntryCount", Form1.TextBoxnMaxMemoryCacheEntryCount.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxLCHairResolution", Form1.TextBoxMaxLCHairResolution.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxLCVehicleTextureSize", Form1.TextBoxMaxLCVehicleTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SpawnMapDelayTime", Form1.TextBoxSpawnMapDelayTime.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "LowQualityHealthHUD", Form1.CheckBoxLowQualityHealthHUD.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bUseSimplifiedVehicleMaterials", Form1.CheckBoxbUseSimplifiedVehicleMaterials.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "SmoothFrameRate", Form1.CheckBoxSmoothFrameRate.Checked)
        WriteTEXCAT_Unknown()
        WriteTEXCAT_Environment()
        WriteTEXCAT_Prop()
        WriteTEXCAT_PlayerCharacter()
        WriteTEXCAT_PlayerVehicle()
        WriteTEXCAT_LCPedestrian()
        WriteTEXCAT_LCVehicle()
        WriteTEXCAT_Pickup()
        WriteTEXCAT_CharacterSource()
        WriteTEXCAT_VehicleSource()
        WriteTEXCAT_PrimitiveSource()
        WriteTEXCAT_UI()
        WriteTEXCAT_VFX()
        WriteTEXCAT_LightAndShadowMap()
        WriteTEXCAT_RenderTarget()
        WriteTEXCAT_Signage()
        WriteTEXCAT_PlayerGraffiti()
        WriteTEXCAT_PlayerStatue()
        WriteTEXCAT_CharacterShared()
        WriteTEXCAT_VehicleShared()
        WriteTEXCAT_NonFinal()
        WriteTEXCAT_Contact()
        WriteNewOtherValues()
        Form1.FixScuff()
    End Sub
    Public Shared Sub WriteNewBucket1and2CompatValuesToCompat()
        DeclareCompatVarialbes.DeclareCompatVariablesAgainBucket1and2()
        WriteTEXCAT_LCPedestrian()
        WriteTEXCAT_LCVehicle()
        WriteTEXCAT_Environment()
        WriteTEXCAT_Prop()
        WriteTEXCAT_CharacterShared()
        WriteTEXCAT_VehicleShared()
        WriteTEXCAT_Contact()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterDiffuseWidth", Form1.TextBoxnCharacterDiffuseWidth.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterDiffuseHeight", Form1.TextBoxnCharacterDiffuseHeight.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterNormalMapWidth", Form1.TextBoxnCharacterNormalMapWidth.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nCharacterNormalMapHeight", Form1.TextBoxnCharacterNormalMapHeight.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorTextureSize", Form1.TextBoxnVehicleExteriorTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorNormalTextureSize", Form1.TextBoxnVehicleExteriorNormalTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleExteriorEmissiveTextureSize", Form1.TextBoxnVehicleExteriorEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleInteriorTextureSize", Form1.TextBoxnVehicleInteriorTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleInteriorEmissiveTextureSize", Form1.TextBoxnVehicleInteriorEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleWheelTextureSize", Form1.TextBoxnVehicleWheelTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleWheelEmissiveTextureSize", Form1.TextBoxnVehicleWheelEmissiveTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nVehicleGlassTextureSize", Form1.TextBoxnVehicleGlassTextureSize.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fMipBiasDiffuseLocalPlayerCharacterTextures", Form1.TextBoxfMipBiasDiffuseLocalPlayerCharacterTextures.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseLocalPlayerCharacterTextures", Form1.CheckBoxbCompressDiffuseLocalPlayerCharacterTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseLocalPlayerVehicleTextures", Form1.CheckBoxbCompressDiffuseLocalPlayerVehicleTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseOtherPlayerCharacterTextures", Form1.CheckBoxbCompressDiffuseOtherPlayerCharacterTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseOtherPlayerVehicleTextures", Form1.CheckBoxbCompressDiffuseOtherPlayerVehicleTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressNormalTextures", Form1.CheckBoxbCompressNormalTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nMaxMemoryCacheEntryCount", Form1.TextBoxnMaxMemoryCacheEntryCount.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "AudioCompatMode", Form1.TextBoxAudioCompatMode.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByTextureStreaming", Form1.TextBoxMaxMemoryUsedByTextureStreaming.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByTexturePool", Form1.TextBoxMaxMemoryUsedByTexturePool.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByMeshStreaming", Form1.TextBoxMaxMemoryUsedByMeshStreaming.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "NumberOfTextureCreationPerFrame", Form1.TextBoxNumberOfTextureCreationPerFrame.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxFreeMemoryUsedByVBPool", Form1.TextBoxMaxFreeMemoryUsedByVBPool.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxFreeMemoryUsedByIBPool", Form1.TextBoxMaxFreeMemoryUsedByIBPool.Text)
        WriteNewOtherValues()
    End Sub
    Public Shared Sub WriteNewBucket3CompatValuesToCompat()
        DeclareCompatVarialbes.DeclareCompatVariablesAgainBucket3()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "fMipBiasDiffuseLocalPlayerCharacterTextures", Form1.TextBoxfMipBiasDiffuseLocalPlayerCharacterTextures.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseLocalPlayerCharacterTextures", Form1.CheckBoxbCompressDiffuseLocalPlayerCharacterTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseLocalPlayerVehicleTextures", Form1.CheckBoxbCompressDiffuseLocalPlayerVehicleTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseOtherPlayerCharacterTextures", Form1.CheckBoxbCompressDiffuseOtherPlayerCharacterTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressDiffuseOtherPlayerVehicleTextures", Form1.CheckBoxbCompressDiffuseOtherPlayerVehicleTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "bCompressNormalTextures", Form1.CheckBoxbCompressNormalTextures.Checked)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "nMaxMemoryCacheEntryCount", Form1.TextBoxnMaxMemoryCacheEntryCount.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "AudioCompatMode", Form1.TextBoxAudioCompatMode.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByTextureStreaming", Form1.TextBoxMaxMemoryUsedByTextureStreaming.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByTexturePool", Form1.TextBoxMaxMemoryUsedByTexturePool.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxMemoryUsedByMeshStreaming", Form1.TextBoxMaxMemoryUsedByMeshStreaming.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "NumberOfTextureCreationPerFrame", Form1.TextBoxNumberOfTextureCreationPerFrame.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxFreeMemoryUsedByVBPool", Form1.TextBoxMaxFreeMemoryUsedByVBPool.Text)
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "MaxFreeMemoryUsedByIBPool", Form1.TextBoxMaxFreeMemoryUsedByIBPool.Text)
        WriteNewOtherValues()
    End Sub
    Public Shared Sub WriteNewOtherValues()
        DeclareCompatVarialbes.DeclareOtherValuesAgain()
        '---APBEngine.ini---
        Form1.APBEngine.WriteString("Engine.GameEngine", "MinSmoothedFrameRate", Form1.TextBoxMinSmoothedFrameRate.Text) '"65")
        Form1.APBEngine.WriteString("Engine.GameEngine", "MaxSmoothedFrameRate", Form1.TextBoxMaxSmoothedFrameRate.Text) '"75")
        Form1.APBEngine.WriteString("Engine.Client", "MinDesiredFrameRate", Form1.TextBoxMinDesiredFrameRate.Text) '"75")
        '!-!'!-!'Experimental'!-!'!-!'
        'Form1.APBEngine.WriteString("Engine.PhysicsLODVerticalDestructible", "MaxDynamicChunkCount", "1000")
        'Form1.APBEngine.WriteString("Engine.PhysicsLODVerticalDestructible", "DebrisLifetime", "60.0")
        'Form1.APBEngine.WriteString("Engine.PhysicsLODVerticalEmitter", "ParticlePercentage", "100")
        '!-!'!-!'END Experimental'!-!'!-!'
    End Sub
    Public Shared Sub RenameTEXCAT_Unknown()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Unknown=(Usage=1", "TEXCAT_Unknown1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Unknown()
        RenameTEXCAT_Unknown()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Unknown", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_UnknownMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_UnknownMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_UnknownLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_UnknownDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_UnknownFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Unknown1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_UnknownMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_UnknownMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_UnknownLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_UnknownDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_UnknownFairUsagePriority.Text + ")")
        RestoreTEXCAT_Unknown()
    End Sub
    Public Shared Sub RestoreTEXCAT_Unknown()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Unknown1=(Usage=1", "TEXCAT_Unknown=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_Environment()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Environment=(Usage=1", "TEXCAT_Environment1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Environment()
        RenameTEXCAT_Environment()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Environment", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_EnvironmentMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_EnvironmentMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_EnvironmentLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_EnvironmentDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_EnvironmentFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Environment1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_EnvironmentMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_EnvironmentMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_EnvironmentLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_EnvironmentDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_EnvironmentFairUsagePriority.Text + ")")
        RestoreTEXCAT_Environment()
    End Sub
    Public Shared Sub RestoreTEXCAT_Environment()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Environment1=(Usage=1", "TEXCAT_Environment=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_Prop()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Prop=(Usage=1", "TEXCAT_Prop1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Prop()
        RenameTEXCAT_Prop()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Prop", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PropMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PropMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PropLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PropDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PropFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Prop1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PropMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PropMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PropLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PropDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PropFairUsagePriority.Text + ")")
        RestoreTEXCAT_Prop()
    End Sub
    Public Shared Sub RestoreTEXCAT_Prop()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Prop1=(Usage=1", "TEXCAT_Prop=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_PlayerCharacter()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerCharacter=(Usage=1", "TEXCAT_PlayerCharacter1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_PlayerCharacter()
        RenameTEXCAT_PlayerCharacter()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerCharacter", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerCharacterMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerCharacterMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerCharacterLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerCharacterDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerCharacterFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerCharacter1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerCharacterMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerCharacterMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerCharacterLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerCharacterDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerCharacterFairUsagePriority.Text + ")")
        RestoreTEXCAT_PlayerCharacter()
    End Sub
    Public Shared Sub RestoreTEXCAT_PlayerCharacter()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerCharacter1=(Usage=1", "TEXCAT_PlayerCharacter=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_PlayerVehicle()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerVehicle=(Usage=1", "TEXCAT_PlayerVehicle1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_PlayerVehicle()
        RenameTEXCAT_PlayerVehicle()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerVehicle", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerVehicleMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerVehicleMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerVehicleLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerVehicleDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerVehicleFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerVehicle1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerVehicleMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerVehicleMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerVehicleLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerVehicleDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerVehicleFairUsagePriority.Text + ")")
        RestoreTEXCAT_PlayerVehicle()
    End Sub
    Public Shared Sub RestoreTEXCAT_PlayerVehicle()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerVehicle1=(Usage=1", "TEXCAT_PlayerVehicle=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_LCPedestrian()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LCPedestrian=(Usage=1", "TEXCAT_LCPedestrian1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_LCPedestrian()
        RenameTEXCAT_LCPedestrian()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LCPedestrian", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_LCPedestrianMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LCPedestrianMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LCPedestrianLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LCPedestrianDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LCPedestrianFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LCPedestrian1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_LCPedestrianMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LCPedestrianMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LCPedestrianLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LCPedestrianDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LCPedestrianFairUsagePriority.Text + ")")
        RestoreTEXCAT_LCPedestrian()
    End Sub
    Public Shared Sub RestoreTEXCAT_LCPedestrian()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LCPedestrian1=(Usage=1", "TEXCAT_LCPedestrian=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_LCVehicle()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LCVehicle=(Usage=1", "TEXCAT_LCVehicle1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_LCVehicle()
        RenameTEXCAT_LCVehicle()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LCVehicle", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_LCVehicleMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LCVehicleMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LCVehicleLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LCVehicleDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LCVehicleFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LCVehicle1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_LCVehicleMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LCVehicleMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LCVehicleLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LCVehicleDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LCVehicleFairUsagePriority.Text + ")")
        RestoreTEXCAT_LCVehicle()
    End Sub
    Public Shared Sub RestoreTEXCAT_LCVehicle()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LCVehicle1=(Usage=1", "TEXCAT_LCVehicle=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_Pickup()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Pickup=(Usage=1", "TEXCAT_Pickup1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Pickup()
        RenameTEXCAT_Pickup()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Pickup", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PickupMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PickupMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PickupLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PickupDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PickupFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Pickup1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PickupMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PickupMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PickupLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PickupDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PickupFairUsagePriority.Text + ")")
        RestoreTEXCAT_Pickup()
    End Sub
    Public Shared Sub RestoreTEXCAT_Pickup()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Pickup1=(Usage=1", "TEXCAT_Pickup=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_CharacterSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_CharacterSource=(Usage=1", "TEXCAT_CharacterSource1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_CharacterSource()
        RenameTEXCAT_CharacterSource()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_CharacterSource", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_CharacterSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_CharacterSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_CharacterSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_CharacterSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_CharacterSourceFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_CharacterSource1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_CharacterSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_CharacterSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_CharacterSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_CharacterSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_CharacterSourceFairUsagePriority.Text + ")")
        RestoreTEXCAT_CharacterSource()
    End Sub
    Public Shared Sub RestoreTEXCAT_CharacterSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_CharacterSource1=(Usage=1", "TEXCAT_CharacterSource=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_VehicleSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VehicleSource=(Usage=1", "TEXCAT_VehicleSource1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_VehicleSource()
        RenameTEXCAT_VehicleSource()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VehicleSource", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_VehicleSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VehicleSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VehicleSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VehicleSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VehicleSourceFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VehicleSource1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_VehicleSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VehicleSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VehicleSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VehicleSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VehicleSourceFairUsagePriority.Text + ")")
        RestoreTEXCAT_VehicleSource()
    End Sub
    Public Shared Sub RestoreTEXCAT_VehicleSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VehicleSource1=(Usage=1", "TEXCAT_VehicleSource=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_PrimitiveSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PrimitiveSource=(Usage=1", "TEXCAT_PrimitiveSource1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_PrimitiveSource()
        RenameTEXCAT_PrimitiveSource()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PrimitiveSource", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PrimitiveSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PrimitiveSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PrimitiveSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PrimitiveSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PrimitiveSourceFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PrimitiveSource1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PrimitiveSourceMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PrimitiveSourceMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PrimitiveSourceLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PrimitiveSourceDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PrimitiveSourceFairUsagePriority.Text + ")")
        RestoreTEXCAT_PrimitiveSource()
    End Sub
    Public Shared Sub RestoreTEXCAT_PrimitiveSource()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PrimitiveSource1=(Usage=1", "TEXCAT_PrimitiveSource=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_UI()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_UI=(Usage=1", "TEXCAT_UI1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_UI()
        RenameTEXCAT_UI()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_UI", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_UIMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_UIMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_UILODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_UIDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_UIFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_UI1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_UIMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_UIMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_UILODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_UIDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_UIFairUsagePriority.Text + ")")
        RestoreTEXCAT_UI()
    End Sub
    Public Shared Sub RestoreTEXCAT_UI()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_UI1=(Usage=1", "TEXCAT_UI=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_VFX()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VFX=(Usage=1", "TEXCAT_VFX1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_VFX()
        RenameTEXCAT_VFX()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VFX", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_VFXMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VFXMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VFXLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VFXDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VFXFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VFX1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_VFXMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VFXMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VFXLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VFXDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VFXFairUsagePriority.Text + ")")
        RestoreTEXCAT_VFX()
    End Sub
    Public Shared Sub RestoreTEXCAT_VFX()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VFX1=(Usage=1", "TEXCAT_VFX=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_LightAndShadowMap()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LightAndShadowMap=(Usage=1", "TEXCAT_LightAndShadowMap1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_LightAndShadowMap()
        RenameTEXCAT_LightAndShadowMap()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LightAndShadowMap", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_LightAndShadowMapMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LightAndShadowMapMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LightAndShadowMapLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LightAndShadowMapDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LightAndShadowMapFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_LightAndShadowMap1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_LightAndShadowMapMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_LightAndShadowMapMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_LightAndShadowMapLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_LightAndShadowMapDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_LightAndShadowMapFairUsagePriority.Text + ")")
        RestoreTEXCAT_LightAndShadowMap()
    End Sub
    Public Shared Sub RestoreTEXCAT_LightAndShadowMap()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_LightAndShadowMap1=(Usage=1", "TEXCAT_LightAndShadowMap=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_RenderTarget()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_RenderTarget=(Usage=1", "TEXCAT_RenderTarget1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_RenderTarget()
        RenameTEXCAT_RenderTarget()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_RenderTarget", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_RenderTargetMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_RenderTargetMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_RenderTargetLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_RenderTargetDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_RenderTargetFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_RenderTarget1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_RenderTargetMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_RenderTargetMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_RenderTargetLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_RenderTargetDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_RenderTargetFairUsagePriority.Text + ")")
        RestoreTEXCAT_RenderTarget()
    End Sub
    Public Shared Sub RestoreTEXCAT_RenderTarget()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_RenderTarget1=(Usage=1", "TEXCAT_RenderTarget=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_Signage()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Signage=(Usage=1", "TEXCAT_Signage1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Signage()
        RenameTEXCAT_Signage()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Signage", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_SignageMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_SignageMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_SignageLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_SignageDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_SignageFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Signage1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_SignageMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_SignageMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_SignageLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_SignageDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_SignageFairUsagePriority.Text + ")")
        RestoreTEXCAT_Signage()
    End Sub
    Public Shared Sub RestoreTEXCAT_Signage()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Signage1=(Usage=1", "TEXCAT_Signage=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_PlayerGraffiti()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerGraffiti=(Usage=1", "TEXCAT_PlayerGraffiti1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_PlayerGraffiti()
        RenameTEXCAT_PlayerGraffiti()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerGraffiti", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerGraffitiMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerGraffitiMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerGraffitiLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerGraffitiDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerGraffitiFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerGraffiti1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerGraffitiMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerGraffitiMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerGraffitiLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerGraffitiDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerGraffitiFairUsagePriority.Text + ")")
        RestoreTEXCAT_PlayerGraffiti()
    End Sub
    Public Shared Sub RestoreTEXCAT_PlayerGraffiti()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerGraffiti1=(Usage=1", "TEXCAT_PlayerGraffiti=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_PlayerStatue()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerStatue=(Usage=1", "TEXCAT_PlayerStatue1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_PlayerStatue()
        RenameTEXCAT_PlayerStatue()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerStatue", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerStatueMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerStatueMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerStatueLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerStatueDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerStatueFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_PlayerStatue1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_PlayerStatueMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_PlayerStatueMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_PlayerStatueLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_PlayerStatueDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_PlayerStatueFairUsagePriority.Text + ")")
        RestoreTEXCAT_PlayerStatue()
    End Sub
    Public Shared Sub RestoreTEXCAT_PlayerStatue()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_PlayerStatue1=(Usage=1", "TEXCAT_PlayerStatue=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_CharacterShared()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_CharacterShared=(Usage=1", "TEXCAT_CharacterShared1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_CharacterShared()
        RenameTEXCAT_CharacterShared()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_CharacterShared", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_CharacterSharedMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_CharacterSharedMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_CharacterSharedLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_CharacterSharedDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_CharacterSharedFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_CharacterShared1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_CharacterSharedMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_CharacterSharedMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_CharacterSharedLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_CharacterSharedDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_CharacterSharedFairUsagePriority.Text + ")")
        RestoreTEXCAT_CharacterShared()
    End Sub
    Public Shared Sub RestoreTEXCAT_CharacterShared()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_CharacterShared1=(Usage=1", "TEXCAT_CharacterShared=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_VehicleShared()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VehicleShared=(Usage=1", "TEXCAT_VehicleShared1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_VehicleShared()
        RenameTEXCAT_VehicleShared()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VehicleShared", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_VehicleSharedMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VehicleSharedMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VehicleSharedLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VehicleSharedDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VehicleSharedFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_VehicleShared1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_VehicleSharedMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_VehicleSharedMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_VehicleSharedLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_VehicleSharedDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_VehicleSharedFairUsagePriority.Text + ")")
        RestoreTEXCAT_VehicleShared()
    End Sub
    Public Shared Sub RestoreTEXCAT_VehicleShared()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_VehicleShared1=(Usage=1", "TEXCAT_VehicleShared=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_NonFinal()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_NonFinal=(Usage=1", "TEXCAT_NonFinal1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_NonFinal()
        RenameTEXCAT_NonFinal()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_NonFinal", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_NonFinalMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_NonFinalMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_NonFinalLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_NonFinalDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_NonFinalFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_NonFinal1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_NonFinalMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_NonFinalMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_NonFinalLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_NonFinalDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_NonFinalFairUsagePriority.Text + ")")
        RestoreTEXCAT_NonFinal()
    End Sub
    Public Shared Sub RestoreTEXCAT_NonFinal()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_NonFinal1=(Usage=1", "TEXCAT_NonFinal=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub RenameTEXCAT_Contact()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Contact=(Usage=1", "TEXCAT_Contact1=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub
    Public Shared Sub WriteTEXCAT_Contact()
        RenameTEXCAT_Contact()
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Contact", "(Usage=0,MinLODSize=" + Form1.ComboBoxTEXCAT_ContactMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_ContactMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_ContactLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_ContactDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_ContactFairUsagePriority.Text + ")")
        Form1.APBCompat.WriteString(Form1.APBCompatSection, "TEXCAT_Contact1", "(Usage=1,MinLODSize=" + Form1.ComboBoxTEXCAT_ContactMinLODSize.SelectedItem + ",MaxLODSize=" + Form1.ComboBoxTEXCAT_ContactMaxLODSize.SelectedItem + ",LODBias=" + Form1.TextBoxTEXCAT_ContactLODBias.Text + ",DisableStreaming=" + Form1.CheckBoxTEXCAT_ContactDisableStreaming.Checked.ToString + ",FairUsagePriority=" + Form1.TextBoxTEXCAT_ContactFairUsagePriority.Text + ")")
        RestoreTEXCAT_Contact()
    End Sub
    Public Shared Sub RestoreTEXCAT_Contact()
        My.Computer.FileSystem.WriteAllText(Form1.APBCompatSourceFile, My.Computer.FileSystem.ReadAllText(Form1.APBCompatSourceFile).Replace("TEXCAT_Contact1=(Usage=1", "TEXCAT_Contact=(Usage=1"), False, System.Text.Encoding.ASCII)
    End Sub

    '----Defaults----
    Public Shared Sub SetAppCompatBucket1Defaults()
        Form1.APBCompat.WriteString("AppCompatBucket1", "VideoQuality", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "StaticDecals", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DynamicDecals", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "LevelParticles", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DynamicLights", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DynamicShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "BlobShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "LightEnvironmentShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "EnvironmentShadows", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "CompositeDynamicLights", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DirectionalLightmaps", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MotionBlur", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DepthOfField", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "AmbientOcclusion", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "Bloom", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "QualityBloom", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "Distortion", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DropParticleDistortion", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SpeedTreeLeaves", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SpeedTreeFronds", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "OnlyStreamInTextures", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "LensFlares", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "FogVolumes", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "FloatingPointRenderTargets", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "Trilinear", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "OneFrameThreadLag", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "UseVsync", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "UpscaleScreenPercentage", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "Fullscreen", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "AllowD3D10", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "EnableHighPolyChars", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SkeletalMeshLODBias", "0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ParticleLODBias", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "DetailMode", "2")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFilterQualityBias", "0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxAnisotropy", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "AnisotropyAmount", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxMultisamples", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MSAA_Amount", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MinShadowResolution", "64")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxShadowResolution", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFadeResolution", "96")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFadeExponent", "0.5")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFadeStartDistance", "2500.0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFadeEndDistance", "6500")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxDynamicShadows", "10")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SunRenderQuality", "0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TrueSunMinScreenSize", "0.2")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ParticleMaxWorldSpaceArea", "25000.0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ScreenPercentage", "100.000000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SceneCaptureStreamingMultiplier", "1.000000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "FoliageDrawRadiusMultiplier", "0.000000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowTexelsPerPixel", "2.000000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bEnableVSMShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bEnableBranchingPCFShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bAllowBetterModulatedShadows", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bEnableForegroundShadowsOnWorld", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowFilterRadius", "1")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowDepthBias", ".008")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowVolumeLightRadiusThreshold", "1000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "ShadowVolumePrimitiveScreenSpacePercentageThreshold", "0.25")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nNumCharacterLOD", "3")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nCharacterDiffuseWidth", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nCharacterDiffuseHeight", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nCharacterNormalMapWidth", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nCharacterNormalMapHeight", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bCharacterGenerateUVBleedMesh", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "m_bGameRenderEyelashes", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCharacterLODDistance1", "500")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCharacterLODDistance2", "1500")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCharacterCullDistance", "0")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bCharacterForceGCAfterBuild", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nNumVehicleLOD", "2")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleExteriorTextureSize", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleExteriorNormalTextureSize", "256")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleExteriorEmissiveTextureSize", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleInteriorTextureSize", "256")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleInteriorEmissiveTextureSize", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleWheelTextureSize", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleWheelEmissiveTextureSize", "64")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nVehicleGlassTextureSize", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bVehicleGenerateUVBleedMesh", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bVehicleForceGCAfterBuild", "False")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fVehicleLODDistance", "2500")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fVehicleCullDistance", "10000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nGraffitiTextureWidth", "512")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nGraffitiTextureHeight", "256")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCAM_MemoryThresholdNormal", "60000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCAM_MemoryThresholdCritical", "75000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fCAM_MemoryBackToNormalHysteresis", "10000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCPedestrianLODDistance", "300")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCPedestrianCullDistance", "5000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCDriverLODDistance", "300")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCDriverCullDistance", "7000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCVehicleLODDistance", "1000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "fLCVehicleCullDistance", "7000")
        Form1.APBCompat.WriteString("AppCompatBucket1", "nMaxMemoryCacheEntryCount", "250")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxLCHairResolution", "128")
        Form1.APBCompat.WriteString("AppCompatBucket1", "MaxLCVehicleTextureSize", "32505856")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SpawnMapDelayTime", "10")
        Form1.APBCompat.WriteString("AppCompatBucket1", "LowQualityHealthHUD", "True")
        Form1.APBCompat.WriteString("AppCompatBucket1", "bUseSimplifiedVehicleMaterials", "TRUE")
        Form1.APBCompat.WriteString("AppCompatBucket1", "SmoothFrameRate", "True")
        RenameTEXCAT_Unknown()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Unknown", "(Usage=0,MinLODSize=1,MaxLODSize=16,LODBias=0,DisableStreaming=False,FairUsagePriority=0)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Unknown1", "(Usage=1,MinLODSize=1,MaxLODSize=16,LODBias=0,DisableStreaming=False,FairUsagePriority=0)")
        RestoreTEXCAT_Unknown()
        RenameTEXCAT_Environment()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Environment", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=10)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Environment1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=10)")
        RestoreTEXCAT_Environment()
        RenameTEXCAT_Prop()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Prop", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Prop1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_Prop()
        RenameTEXCAT_PlayerCharacter()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerCharacter", "(Usage=0,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=40)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerCharacter1", "(Usage=1,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=40)")
        RestoreTEXCAT_PlayerCharacter()
        RenameTEXCAT_PlayerVehicle()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerVehicle", "(Usage=0,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=35)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerVehicle1", "(Usage=1,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=35)")
        RestoreTEXCAT_PlayerVehicle()
        RenameTEXCAT_LCPedestrian()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LCPedestrian", "(Usage=0,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=30)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LCPedestrian1", "(Usage=1,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=30)")
        RestoreTEXCAT_LCPedestrian()
        RenameTEXCAT_LCVehicle()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LCVehicle", "(Usage=0,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=30)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LCVehicle1", "(Usage=1,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=30)")
        RestoreTEXCAT_LCVehicle()
        RenameTEXCAT_Pickup()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Pickup", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Pickup1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_Pickup()
        RenameTEXCAT_CharacterSource()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_CharacterSource", "(Usage=0,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=100)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_CharacterSource1", "(Usage=1,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=100)")
        RestoreTEXCAT_CharacterSource()
        RenameTEXCAT_VehicleSource()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VehicleSource", "(Usage=0,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=100)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VehicleSource1", "(Usage=1,MinLODSize=1,MaxLODSize=128,LODBias=1,DisableStreaming=False,FairUsagePriority=100)")
        RestoreTEXCAT_VehicleSource()
        RenameTEXCAT_PrimitiveSource()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PrimitiveSource", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=100)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PrimitiveSource1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=100)")
        RestoreTEXCAT_PrimitiveSource()
        RenameTEXCAT_UI()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_UI", "(Usage=0,MinLODSize=1,MaxLODSize=1024,LODBias=0,DisableStreaming=False,FairUsagePriority=100)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_UI1", "(Usage=1,MinLODSize=1,MaxLODSize=1024,LODBias=0,DisableStreaming=False,FairUsagePriority=100)")
        RestoreTEXCAT_UI()
        RenameTEXCAT_VFX()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VFX", "(Usage=0,MinLODSize=1,MaxLODSize=32,LODBias=3,DisableStreaming=False,FairUsagePriority=10)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VFX1", "(Usage=1,MinLODSize=1,MaxLODSize=32,LODBias=3,DisableStreaming=False,FairUsagePriority=10)")
        RestoreTEXCAT_VFX()
        RenameTEXCAT_LightAndShadowMap()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LightAndShadowMap", "(Usage=0,MinLODSize=1,MaxLODSize=16,LODBias=4,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_LightAndShadowMap1", "(Usage=1,MinLODSize=1,MaxLODSize=16,LODBias=4,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_LightAndShadowMap()
        RenameTEXCAT_RenderTarget()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_RenderTarget", "(Usage=0,MinLODSize=1,MaxLODSize=32,LODBias=3,DisableStreaming=False,FairUsagePriority=0)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_RenderTarget1", "(Usage=1,MinLODSize=1,MaxLODSize=32,LODBias=3,DisableStreaming=False,FairUsagePriority=0)")
        RestoreTEXCAT_RenderTarget()
        RenameTEXCAT_Signage()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Signage", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=50)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Signage1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=50)")
        RestoreTEXCAT_Signage()
        RenameTEXCAT_PlayerGraffiti()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerGraffiti", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=50)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerGraffiti1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=50)")
        RestoreTEXCAT_PlayerGraffiti()
        RenameTEXCAT_PlayerStatue()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerStatue", "(Usage=0,MinLODSize=1,MaxLODSize=16,LODBias=4,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_PlayerStatue1", "(Usage=1,MinLODSize=1,MaxLODSize=16,LODBias=4,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_PlayerStatue()
        RenameTEXCAT_CharacterShared()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_CharacterShared", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_CharacterShared1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_CharacterShared()
        RenameTEXCAT_VehicleShared()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VehicleShared", "(Usage=0,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_VehicleShared1", "(Usage=1,MinLODSize=1,MaxLODSize=64,LODBias=2,DisableStreaming=False,FairUsagePriority=20)")
        RestoreTEXCAT_VehicleShared()
        RenameTEXCAT_NonFinal()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_NonFinal", "(Usage=0,MinLODSize=1,MaxLODSize=32,LODBias=0,DisableStreaming=False,FairUsagePriority=0)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_NonFinal1", "(Usage=1,MinLODSize=1,MaxLODSize=32,LODBias=0,DisableStreaming=False,FairUsagePriority=0)")
        RestoreTEXCAT_NonFinal()
        RenameTEXCAT_Contact()
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Contact", "(Usage=0,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=30)")
        Form1.APBCompat.WriteString("AppCompatBucket1", "TEXCAT_Contact1", "(Usage=1,MinLODSize=1,MaxLODSize=256,LODBias=0,DisableStreaming=False,FairUsagePriority=30)")
        RestoreTEXCAT_Contact()
    End Sub
End Class
